#ifndef ERRORS_LIST_H
#define ERRORS_LIST_H
enum ERRORS_LIST
  {
  OK                             =  0,
  NULL_POINTER_ON_DESCRIPTION    =  1,
  NULL_POINTER_ON_FIRST_ELEMENT  =  2,
  NULL_POINTER_ON_LAST_ELEMENT   =  3,
  WRONG_AMOUNT_OF_ELEMENTS       =  4,
  WRONG_POINTER_ON_FIRST_ELEMENT =  5,
  WRONG_POINTER_ON_LAST_ELEMENT  =  6,
  BAD_INPUT                      =  7,
  NULL_POINTER_ON_AMOUNT_IN_LIST =  8,
  NULL_POINTER_ON_FUNC           =  9,
  NULL_POINTER_ON_NUMBER_IN_HASH = 10,
  NULL_POINTER_ON_MASS_OF_DESCR  = 11,
  NULL_POINTER_ON_HASH           = 12
  };
#endif
